---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 22.19.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        replicas: 3
        podSpec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: blocky
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gatus.home-operations.com/endpoint: |
            path: ""
        hosts:
          - host: blocky.${BASE_DOMAIN}
            paths:
              - path: /
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
    # ToDo review blocklists
    blocking:
      whitelist: []
      blacklist: []
      #clientGroupsBlock: []

      clientGroupsBlock:
        - name: default
          groups:
            #- default
            #- default-ads
            #- default-tracking
            - default-malicious
            - default-suspicious
    ## set stopAll to "true" if you do not want to use blocky
    # and/or disable its service
    global:
      stopAll: false
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true
        annotations:
          gatus.home-operations.com/enabled: "true"
          gatus.home-operations.com/endpoint: |
            group: services
            interval: 60s
            ui:
              hide-url: true
              hide-hostname: true
            conditions:
              - "[CONNECTED] == true"
              - "[RESPONSE_TIME] < 100"
            alerts:
              - type: discord
    k8sgateway:
      domains:
      - domain: "${DOMAIN_0}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
    defaultUpstreams:
      - "https://1.1.1.1/dns-query"
      - "https://1.0.0.1/dns-query"

    conditional:
      mapping:
        - domain: ${DOMAIN_1}
          dnsserver: 192.168.1.81
    bootstrapDns:
      ips: []
      upstream: "1.1.1.1"

    queryLog:
      type: ""

    configmap:
      dashboard:
        enabled: false
      datasource:
        enabled: false

    cnpg:
      main:
        enabled: false
