apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guides
  namespace: guides
spec:
  interval: 15m
  chart:
    spec:
      chart: static-web-server
      version: 8.12.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: guides.${DOMAIN_0}
    image:
      repository: ghcr.io/itconstruct/guides
      tag: 0.0.1@sha256:f7181bf033e03537cbab3067d61826beaad94d3e01c5008819c20dc5f888fa0e
    imagePullSecret:
      ghcr:
        enabled: true
        data:
          registry: ghcr.io
          username: "${GHCR_USER}"
          password: "${GHCR_PAT}"
          email: "${DOMAIN_0_EMAIL}"
        targetSelectAll: true
