apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:2xaQi/DAub2cB5hFgPmxQ2CBYkZsnvUQyYQkuLcoiMPFDMUyTXs6nElcPGTZcSSKU0SZlL4m6B7GAywqQ3IqinOZlltaEvKHt41We7QM0E3nuLsDbSiEnXhz0hP0cV/MVqIw+ux+BtKOGQ36V0laWlYOsFCrZ1Ayy/Y4LqbKDPM=,iv:o/WGVWxwRFeRnFPK/NCrtXrRIxxcdBU5w6rsVAj1syc=,tag:JmGM/lcKsxfeT4iS0ELrbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQjgwMW41M3o3RWxYNCtO
            ZEYwTXZXemdvdG9jN1k4OG1Yc1A5QkxvK0hFCmNqSDA3WjdhYk9ZdEdzVHRzY2VT
            aVA3TEhMeFpRZzRDSFRtYnZzeWdpYncKLS0tIEhEQmNYOVZ0bHpWZDBtb29MRWQy
            NWRnSEJLRnlKS0xLcThuLzhPZUlOSzAKMZS3SgHbefSf4E4FNLUs/HoqpTMKZcn6
            JMqqJJecN7sL76HQWIuYKicSF2dtQu9GcJfK2Z4R8v+x0Q595qb1nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T10:25:54Z"
    mac: ENC[AES256_GCM,data:HqtydbD2wh+Uh1l1adUSnazXqeRPfGVb8J5xUoJAduqM4fOf17XWdy2HF7weOTSRuaE8bI04AnEzP4RJq0PsW+pufuBpKXyWyGEaJxK/6KtbgMlVrQ42Gm2f5nYlLYQJquAwWPYGau5BmYAhP4QJysjYP0L4ZD5v6P/P+Vb+QdM=,iv:pNy5qXMfi7ZF8yWDXqMGFtP+BxR9dvbAJinD3oCuIMI=,tag:vAvh5w/ZKojI//2pExtoGw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
