apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:+6mMfUcNahsy8AVvnaia4piiQMl9lFtax5ZFiosrIzvj6GurYesb/t6F+xFs1XZO1GIpMHiJlIYcSoXeqFEjy6HPw2ZKos/n9gfw2/7hguUU881pfG6T4AhCqibukUhBYUcxZ4XnLoELPyuGzFH7tLVrnKnJts72zCtJwxbwK68=,iv:HH68fkVi0KZp6P1d4FThpiYrdtf9frVFJ1pHgxh/W8w=,tag:hw4EjoNAXQzGSIUU/FTHLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT0RtNkFxb2RIVUYrMnVJ
            cUczdmhiWk8rUmNOaU1TK0twTUNwcXkydUVJCmpJMzR4MGZOTlBDV0tHZWQzUjk2
            a0lVOStTRWZPMzNzQW8vWE1DVktOTnMKLS0tIHhaNjRzM2tDZUhmMFhtWlpkbDcv
            QjduM0RNaFZsS2xwRG9TWlU5WTdqRXMKBJFvlOFkqypnWl8FKg7ClXvXkvuj3RDf
            g8HFRvVNoVwfNJO9hLi+g8osom6gQGtp6ih8a8VM9VgJK/To9XkxHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T11:07:19Z"
    mac: ENC[AES256_GCM,data:xwyvIo/sN7eiEa9JLl8Wet3YsjueeMZlAkjg1rV/KOZO5b1HHz+ICFeb2ibRbm2o2UIu/MJwgRQgJxohcCbC8fvnUeQEXVDrx/QT4wFrx3Dk+b9ITtwbYoHjmxUnbfUmPi4x4FVQSyFAbVkeZhVC0NnvaZ4v7i9ssFJTNqeUj/I=,iv:Yp/Mz4/K2P1gfX5apG4LDq/IyBJx7q9ouYB1iNd3y+o=,tag:5VBhZKyIQxU9Wm07YujFoQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
