apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ZekFVjpHFQrYxdy/KR7lqFCtolZd6/3DBZzZS1F+/braDE8QNY6GHyxhoNIPqlFfjNG00ynpSxTkw3Lf4jva6jA6oLahcCFFu7AEBhRq6khUABGZug05tCuRXLUEWZVLyvP9tX8q/9S+Nx+LSGlNGfbSg8C+Pl+7DQUsrW0a7Xw=,iv:KE+jL3qZXPKYWp6zcxVKSTC9qY9wdk0T8w+16ZwV9FQ=,tag:SV0z99dUBhYANTjZbvKVCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdFJUcHBrT1FuSDlNQ1l2
            WGwwQXhOU0RhamZqMUJ3SHB1Vkh2UnNJQ0dNCm84ckY0YlRXVlJYcm5HN0R2VmdS
            NDdvdEpJc0d2aWo0V0JGRStKYThTMjQKLS0tIEwwOVU5MER1MTc1SWg4UExPMCtn
            N3l0N2YrR3dCblVOZFJtbStYbFc1VlkKYMmXqsvaOAzguWK0P23pgQTS9idiK/VL
            t9IW7iQXVTOkrDKtW1AdLbsGwM9qdw+7Cab3+Rj9fxkzCJkG7X0xLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T10:37:55Z"
    mac: ENC[AES256_GCM,data:viWArY4MVqguv6Z9lhujERlJpCquahgoGCMmcyg5OSgLBNIfE7bb7QiYLDO39CBBFdDaVwH1kg6u3AiJTcKbDDQI2cDWPabsAv4qbUPpespansEld6c5OjrSKkWihPrAPZV4wIOVDOArGQd0yNs1Jz01yclqQdO+XKkFU/CfMdg=,iv:w5noluL2x6xgF9If25/bcLfSE55Us0plz2ctooexHaU=,tag:PxWQZl9uKCLrPx0fBNsVgg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
