apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FfOIFCd7Brer1nCE64YOL7rnMPtEG8kMNxyhZLetclEP1OEVXX7Di2MjQVoWY64Cf7nrG6MR8WZ9fd3Cu7A+Egtf82CPws+pE3HWu+SI+carY4oTr57VkZBJJP9H0A3RvDNaFmlP4B/JUTmdKP1JaTanV4d8YJNEfh16VxjEKN9sjptFKe9AwTssxtqaUxMpX5SrxeIj0J1P8AIeQqTUUiMlqJDPyq6eKhIFyMB4GXnRC+qCgODxgxGUZOWs7LAk1lbY9V/JbO6BN8GfC0Ua/He3nKCuQmOq16K/i8dTC5E1GH42zE4BIPLv+N5e9R4l3pI/ifE8uI2JLMTabxPQ5BLNYlDKtRVM5TGowRaGUv+gOu+nsX4rcMBmR6EuI47M,iv:LZf1a2z3bM+3Qc+8dsluvj04c+0ZadxFuKxkRkpq+fE=,tag:iKBhKyhNg3++Rr/Qdmc2HQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vS6yh9MASQcXjbC4Gm4SnwqMPgykABsqzkQUDANpZnaSTcRu3cZ+Hdw9NRG5qdV7u9MgORFrmzB2sGgXP2rWDqQ/0xEIfQYy47Ks2Jm6jSXZktn4/CNCK3S68tD5yv3r9FqEIIBanZyf9j5Gueuy8gCvUvZhnwdcJcznkcdOa4BNR2Qa7MnQq6fH/USv9PLwoFU7fiVq6/BWSNvw/tOgbFUYPsq75OqZMMHlA5+gFc4FQLyJlSo1yZy1vNojrfMcEjFwtPg4MKCcpZ3FTQ==,iv:faQpTruDaIfpRtqpyIm7Bs024Enoz0cTFxn/5BN/tWI=,tag:10YCzvmbidW7/jhrfvF5Sg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZrWRw8TmEAsfypSs3/adpsRSArRHZxNjemMPjGBEJW/X17JssiFcd8w5PwJ4xEIS7TqUxmVV3bjk0f7LJ0IYD4YxLE4QJfKIGcc71xCVCB42JAHmG6J1X9tv+gnPk0jUAYsSdmUnt7oedF0/FjKw70BEF3iWrQ6hB2rLkpxtGzXUTbKiyJeNWz8SI2FDP1OE3cavJQBdJzIwDtegt2bi9yXfD2ujLGIOvjKq,iv:lfJj5Lni0BWXHlGmh7GC0cktwi+C4q4CoV1MhZ0m4fs=,tag:trUM34L+cRN3jA0R26aoMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eXFSTXVKeURHTmdLTkhX
            eWpUaDFob1FZNzI5MXUyRzZrQ0VGWGRMS2hNCkNYQW1qamlQTVFwQTMzakluNjhh
            MWpXNENLaDB0djRtSmpzN0RjaVRhSDQKLS0tIHM3SXNHcUhWQkFjTENQc0l0UTdW
            OHJPcnIxV2NSK2JSRkVaR252ZHlDSFUKfzPbB2AfaMdzh/yVndA6Vbd9Pr9MaLGB
            hDwxyEEZjqB9kDk+fBXfb4zIu1dug2n7lsBHSAsylRLBCalSAfGVdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:29:30Z"
    mac: ENC[AES256_GCM,data:JOf3Wrjgvbcvij+rMtdKxXVQjwO7qivsHJ0TJIkuESXTf2u7HHHr0CHNuBLcqSK2t4e3l1fhjGhi6ZnAoarBFfZv9IzPyaZ83RoffcAUedjIc6z5aRbjuO44MrWrAgYewnZxQ4EEf3OfBa42r0qYLgpyju107G/AYyu+ewnzlXw=,iv:GRmKejZifv6pvzRvAdSkLPr6VIB8Nd/xAISRg/Br97Q=,tag:me9PBA9HMtxtkeiOAgcYrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
