apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S1HPeVhMXxpgF5Eat4AOUwXKQqadAeCe5NKSIFcqelAP/TVQiLQdGt8w4w2YnKf1avrva6m1GITkfsreIiroYMeIqIi7WbJYS7pIiKFvvfBuK7BcfaXkv5DVnIBrOX/69pZ8OTsiHNBRvarmr5tRD3wC/KouK5SYTQazkZ3W3lI7iO5k4oN+gK0gHp9da0vc6uYHttSu8JqqExeSHRhntvx2ULUJtzCIDnQYzpZOCWvLNum2LUgAAJRsbpbLIHq2y2PrvIH1VpY3/y4Op901aJ4j5HDKJVnqB1JV6i7CrnM4j0OcAAC98NGQCO2ohZ4QJOgqMrf3SFeVteMG32znD09HOahuJ5Ab5L62cIzZIinNTQYudly8H8AF4opJNUiZ,iv:9k3/2TrZZZXgq3VkX85hMphCS6w2IqPB7D1yBE3Cw1g=,tag:OSgVvCFcQdl/UyciM+Ml/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:FgRFOFjOfhkkWmE25E2+JfKvBDRLUbPGb0JGL/iZwbMSrC7h0yUb5x3riIO5q8Q0HxwhHdRzaH/9LnT6C0eRz92tUCbHaE2X7z/XxfOCIFUZana3FQbO8CJ4q4cST7tdf6cNC53hFljPN0s3yUndxltCd3H6ucBgsjQZDZKyFaQtNfU/I0jzPWqHd9aaQrbb4lhC9xUBM8Dq06lTrFJiuxtBcqPxSQH1nOKA3TTIKDuWCmsBK0KoOfPkRR91+s9Zzv738d9m7VIcunMfbw==,iv:z+4STiCvikiCk2KW8ejRzkbcBN2Ngb83UHgoWxlEMyE=,tag:/bsxGPceO93asxGHZEpyvw==,type:str]
    known_hosts: ENC[AES256_GCM,data:bYdKJPYzpxTGaSELgDw1woe78kx79Dj54RU19J3LkNM+bKCnrk/UsuVvu9cHvETVAo2At4K5/YqILw/s5xpLpw3ruBAD0UnxEuzVYCFVJd7vzV+vhCDhDiMmXNbV2I4KgmxCdb03KAN7D3rl4HMn+Xxs/8Ws9vBLLLjv8AG1nqoR83FTPase4MtWtfuPEGyJbSYv/rmtNjjOVtETIELqZbD0odFvLWZQumHR,iv:fbrgV+TyQ2ma6CpESwv9uTKiyGuvsOw3W6wF5vC+qyo=,tag:NBGaILbxzRJ/Ljpye19TCA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYmhuNitzU1BEUTB4M2J6
            NGJTQTFjMlM4Q0FBQ1pUemR4Mzl6RDc3ZFE0ClNGdXdmVnV3NjEwYnBPQndaSFVP
            Ry9tNVNRR2FKZmxFSW41NCt3MUlUVFkKLS0tIFpLTFVuN0tLbGNVcXFhYXErYmhU
            dm95a1pMYkJOaGx0MlJBaW5UdEdCUGcKrv+m+Wl4Su2AzPoObNNuIPQBIlkg/pmL
            y8IPT85itjAkNarQvqYEncmERprnsZFr4ekY/oU6DR/ZE/OxEg5faA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T10:00:19Z"
    mac: ENC[AES256_GCM,data:LtuaNW5sCdW1rxPYv8YkUr7ApBuH2i6VOG1vyYaeN1Q6H25ah+jBZpFNQ69ktvh/5iP1RBDUXMiZb87zrCN4bIF0nKMQuEpS7mYUkQU3R5UOjqvtZszmLnZVsXmwWbQV8tOwZj3v8u7rC23SYNjoxWq4lM9hiqTkY6tDqnPjqDQ=,iv:rE8GEvRrnDYqvuWdig5N/4LdXarTlSZu2qzMpuaIwhI=,tag:CYsTJenEt1vn64OnOK2HOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
