apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LclPV4rLr830RRD0EZxyCGvISA1db+LEZDlRiMczlfPP99meZSAmKsb1iPhlaN2U4POkzs1IRRuZVEYBGOzTXM3bmnx4LxCDUU5WtXIER9rgn/i3umCS/HhckWPRR6DL16Ui4wLoggCO5vIvU/NhVZobU3RxjnOhRilWACNsbPjegzmK+J76fCKC0NKD0HoPpUWJWSkWKFwV3dsDrdK7ClYGWUHUZc9H9B9DnEiqGR1CUjN2bAXsh+UVii3Su6YgqdwA9y8zcb9Tg2+igJXWHZ5Ps9L8AY3nDouRlYK8cx/4WWvnhtBnmFqgsEHoSaIK+VgAyDViSgRQvoaLM+y/FGwjVw6kc6f5BnvJZMUSk7iJN4505Qqk4heZcLe25eiy,iv:5okd0Z06/5EQjlumzvK8F7d4I8Nq6iYj5CAAuPGDYZs=,tag:yhsHgJP1an9g8245NWtVpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:+EHIzUGdZnCh6AB6dUDThdBb0MdNhZ2Vc3F+Xo6ao2AQzHUnEzzuW2xeYrIEe9nAIG5CdFius7bciuaHWVdc916lQEFb3w6ZsZ2cVC91tTwwewoZ6pCxb7NipYSSgAniv1ji0bKG+uMwuNCxnkWK8VBrFWl/5rCO5ZMpiLNyRN8m5wwfZUUFJJY9//JV6a9RCoog9WId2FwMibRV2mp8lgCTHTfX+IFZOc7QbWubytMHW98ExA41IuX6j7UOc8X3Zm0GM+opzJMYshnKog==,iv:0nAOUlEHhwklB4or3Ku1KZQZk4j72twU5AFEOlsAdao=,tag:XLOkLnNFb35rrpXM8Xebqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1+BjlSK3FtpgFrhKThKa8C56DPszJcB6pQiRn1gXYNUbyd6TmiksU29h8LknTJ5uNt4gUMyalvd/K/Whnxl/P2bPgxZfLoVo7ay0ttJPxTdPHCcZ+BRSBk+rOV8AoX2KUDWxL3LjFrQmHj9HnUcMCIPwnQ1XjkazuGQLyMa9EFMkeYR4VucViN9UDt0tSdVGZEHtflo7IOc4R7WNOrMHazaOhzVfJTobRobj,iv:dmAAIY6LWv6Tj6MVONUToBJcsDSRPv2wcjUrhIub88w=,tag:0Jspaf+FZJ9O77smDFukog==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMkV3UG9mcXk5Y1JZa0o3
            QnJESE9BQmdpUURVbW8zYlEzK1lNQ2JidVU4ClVrbENtR1NYYzdqZ2xBOHBpcG1K
            UlZ5OEszSEF3U3lWaFhOZGU0Q0ZiQUEKLS0tIElGWXJ0TzFzQktib1NPOE9YcEp0
            eWQrdndPNmMvTzJaeEtVeTZmY1ViN0EKEJVYkqObSV1VKfSio7JFAKYRgNR6Z/s1
            eQc+lS7Sws6aiHAVsnf+5OOnvEFXxn3GTvGQnbRy77z2G84E/JL/8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-29T10:43:00Z"
    mac: ENC[AES256_GCM,data:jh8hfnnjOHx9KY7SpvqNVZeUzn6aGowvxEZZd/gh0n+nBOshDdmAkMWNBgFee61LD7hLTLjtUUHTgI+F31JArECZSdBNco2olJnXq+8COp1cGcxusvEQa2tz7CCPzl/udsGCsykd/+a8bRqahBXk55Y7WfoMVAQlrXb0+91b73g=,iv:n267F9gViacHn29QSI5359pUalzmw+BTu98EcxMkKOY=,tag:riO5etLbpgU9DAzVseCWig==,type:str]
    shamir_threshold: 3
    version: 3.13.1
