apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gXWcUrRrXDq/i5Urssugoynqj5w1wWNFlGVTBtLB7dDayjDfIc3YTA==,iv:vUjoTdFMOEgSR/ZboZopWSMt7acK/vpLaE0B5ifHRrA=,tag:CgiPCPcIiLFtBJa/XR7xrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdE52RXdBM0pta1h3S1Jw
            T1AyWEJ4KzhxRHEvSEx2M283alZySlVlNkFZCnFESHRzWllpa3NpbzdoNDRmMnBV
            NjBHQ3NTQ0JBdk5ZQjFmQ3VKWlJEbzQKLS0tIHViRTZsTTN1dTZXK1liWGZYNkd0
            anJKcG1vT2VCbWdVU0cxeHlOek1ydVkKw2C93Y6IWKV3waxJJlX6RGV6gLCF5h5C
            qXIBZz6yqASTbgogmlEyz0JAgiQ83eZpSo5MUlqYYz2ggfEX5yjqxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T09:23:55Z"
    mac: ENC[AES256_GCM,data:uCdMNKtdoND5ztGZpXIdXZVfQiyKxFhB0fM4+mv2U7H6lMFmTrPid33mr2ecJJw9+z9Ct5Dukq63a/UJl1w7uQ2zB5OBL1AOvHDXdc6biQEVo/Zh94SpsXbszckHaDM4xayNjGA7O1AKUz20AQdiphI1WQn+9WaaZgV3bpLBaNg=,iv:5LUjQJZvgLEOMIi6owWu4A8zq5ptXcr8Oe4G9zYt7I0=,tag:N26m1N+muXuqulNCbfpRNg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
