apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fkuGTuWrzCEaETYLfhY6y6mA1cXja/KBMJZoL/z2AuKwX9RMtVfUFw==,iv:ZyTPCLusX2C1xXLssOHsAn0cIN+dR1LXSmMbzSmqj3E=,tag:Gf8IY2um03sPSRq9BM/sMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakdiMDM1S3ZFR0NPYjk1
            Qy9CZkFYMDBwUkl3TEJrN2lWQkJ6U0w0Y1dVCjBpYm1pbjJEOGhTRW41bTU4OGwy
            ZVhVSW9FSmVEc0hRYUZPMkJHUjBVMHMKLS0tIDEzRklJU2JMdjZvWm9NZGU0OGhC
            YUY1NENJRVhXbUdrRERULysxc0RXQUUKzcA4a/ZWRyyiBqE/Voi/L7h3ih9K1Bo+
            o+NP8AVUUWv6YjKgk+DlLv+40gsWV7Tf+k/nQ2OzBj9Fjar+ts4yng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T09:26:48Z"
    mac: ENC[AES256_GCM,data:aAVTVFgFip640LpfXpr9mTNDS4YJWLCOtfTB6kqnxAowA+PRM1Jyge+tRrfAVEUukc89/w1sY/k/wq9qZDlLaCBW3U3fjcvBolZnJTOG0VufVX8Cw3EfNXcEIfi5W7l4p2rQFMaRO9yttc+7rueu1WJ+0V+m7No9Kkmb55D38TM=,iv:Ze3QFn46j8DpJxUgLqcJI4k64BFyNfweBobOEKDvF9Y=,tag:MTdIAgjIbsFd5B4W18Ey9w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
