apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XCuGSVTqx52ZSW9yVH+/cpUp2R7jyhCkgnrFRx3vNzuz6yIOKHfwJA==,iv:AU9ta/TyjydNvfuh1K6aHIFNmcpNIGlyk8Q83vizvVI=,tag:kB92Zv6xIafots5ky40O1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWdyc085TDNwN1ZMUk91
            dzFtOGVFNnFidDk3KzB2ZTFRZGdKQjFVZ0d3CjdPdWFvMDFxRHYvWlZYcmV6NFp1
            dEFWTVlsamVia3kvUUxIcnc0L0lxWmMKLS0tIHA3SDVnbWxOamprTXl2SHEwVkdT
            WEF3ckFPUlBKaVpMRXI3MFJPN25YbmcKBTl1R12eQIYNcBidpiUAGUDsBn1KaCb9
            lxYEEDOh0mZBv7j2FnpNvrsfuxjy5B7rHHHEu4k/BywD0a4J0eMXqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mfh4698xzqlp2jvkzdagdqc85v2gz0r75uaz3pkh8twchdvgnp7se9u8kr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T05:41:10Z"
    mac: ENC[AES256_GCM,data:aG7KYmVrkC2zlcK5aUVmvsAyOrnubFMp3FaQ0eZtoe1RqYD41oKUSWywKDQbe2J8g1D7Q92HekKSvKX7xxTdVRkPQparWYdRFmSc60JOpsXK2GWBL0jGReEy40+IpiRmfQoeEYGuu0n5r0XdHYJvwqG1Gj25oaxCwbfdgsljG50=,iv:3jnAseaRKofW2UeZ5cs5Lv8UFPNAOzm+GwIL/jpuO+o=,tag:fpAQMJcUi8qH9VCcAyCttA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
