apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
configMapGenerator:
  - name: gatus-grafana-dashboard
    namespace: gatus
    files:
      - dashboard_gatus.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
