apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 20.15.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: calibre.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "domain-0-le-prod"
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-calibre"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - name: config
            type: restic
            credentials: s3
            src:
              enabled: true
              cacheCapacity: 5Gi
            dest:
              enabled: true
              cacheCapacity: 5Gi
      books:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: "/mnt/docker/Media/books"
        mountPath: "/books"
      calibre-library:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: "/mnt/docker/Media/calibre-library"
        mountPath: "/calibre-library"
